---
- name: lb
  hosts: [loadbalancer]
  sudo: True
  #become: root
  any_errors_fatal: True
  gather_facts: no

  tasks:
    - name: install packages
      apt: pkg={{ item }} state=latest install_recommends=yes force=yes
      with_items:
        - nginx

    - copy:
        content: |
          upstream backend {
              server 172.17.177.100:8000 max_fails=999999 fail_timeout=30000s;
              server 172.17.177.101:8000 max_fails=999999 fail_timeout=30000s;
          }
          server {
            listen 80 default_server;
            listen [::]:80 default_server ipv6only=on;
            root /usr/share/nginx/html;
            index index.html index.htm;
            server_name _;
            location / {
              proxy_pass http://backend;
            }
          }
        dest: /etc/nginx/sites-available/default
        backup: yes
      run_once: yes
      notify: restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted


- name: workers
  hosts: [workers]
  sudo: True
  any_errors_fatal: True
  gather_facts: no

  tasks:

    - name: install packages
      apt: pkg={{ item }} state=latest install_recommends=yes force=yes
      with_items:
        - python
        - docker.io
        - git

    - name: Build hello_flask
      docker_image:
          path: /tmp/hello_flask
          name: hello_flask

    - name: Run hello_flask
      docker:
        docker_api_version: 1.18
        name: hello_flask
        image: hello_flask
        state: started
        net: bridge
        ports:
          - 8000:8000

